# Generated by Django 5.0.3 on 2024-03-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Специализация')),
                ('image', models.ImageField(upload_to='doctors/', verbose_name='Фото')),
                ('year', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт работы')),
            ],
        ),
    ]
