# Generated by Django 5.0.3 on 2024-03-11 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_carouselitem_category_servicephotos_services_reviews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServicePhotos',
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic.services'),
        ),
    ]
