# Generated by Django 5.0.3 on 2024-03-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_delete_servicephotos_services_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='doctors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic.doctors'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent_review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='clinic.reviews'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic.services'),
        ),
    ]
