# Generated by Django 5.0.3 on 2024-03-13 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0005_alter_reviews_doctors_alter_reviews_parent_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField(max_length=15)),
                ('position', models.CharField(max_length=150)),
                ('cv', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.PositiveIntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('descriptions', models.TextField(max_length=2000)),
                ('salary', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='doctors',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='doctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctors'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clinic.services'),
        ),
    ]
