# Generated by Django 5.0.3 on 2024-03-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_appvacancies_questions_vacancy_alter_doctors_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appvacancies',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.vacancy'),
        ),
    ]
