# Generated by Django 5.0.3 on 2024-03-13 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_alter_appvacancies_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityDoctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='doctors',
            name='education',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appvacancies',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='questions',
            name='phone_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='descriptions',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='doctors',
            name='speciality',
            field=models.ManyToManyField(to='clinic.specialitydoctors'),
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('descriptions', models.CharField(max_length=256)),
                ('image', models.ImageField(upload_to='works/')),
                ('time_treatment', models.PositiveIntegerField(default=0)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.doctors')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.services')),
            ],
        ),
    ]
