# Generated by Django 5.0.3 on 2024-03-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_specialitydoctors_doctors_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='doctors',
            name='description',
            field=models.TextField(),
        ),
    ]
