# Generated by Django 5.0.3 on 2024-03-13 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_certificates_clinic_equipment_independentratings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='materialsclinic',
            name='image',
        ),
        migrations.CreateModel(
            name='ImageEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('materials_clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.materialsclinic')),
            ],
        ),
    ]
