# Generated by Django 5.0.1 on 2024-03-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0011_delete_equipment_delete_modelequipment'),
        ('clinic', '0011_remove_equipment_image_remove_materialsclinic_image_and_more'),
    ]

    operations = [
    ]
